info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T19:24:22.007Z"}
info: Connected to the database. {"timestamp":"2022-07-14T19:24:24.430Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T19:57:34.913Z"}
info: Connected to the database. {"timestamp":"2022-07-14T19:57:37.270Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T19:58:58.724Z"}
info: Connected to the database. {"timestamp":"2022-07-14T19:59:01.289Z"}
error: 
    status - 500 
    message - TypeError: "hashPassword" is read-only
    at _readOnlyError (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\readOnlyError.js:2:9)
    at _callee$ (C:\Projects\Socially-App\src\services\/user.service.js:9:3)
    at tryCatch (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.newUser (C:\Projects\Socially-App\src\services\/user.service.js:6:21)
    at _callee$ (C:\Projects\Socially-App\src\controllers\/user.controller.js:13:36)
    at tryCatch (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Projects\Socially-App\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-14T20:01:58.153Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T20:02:39.193Z"}
info: Connected to the database. {"timestamp":"2022-07-14T20:02:41.689Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T20:02:47.040Z"}
info: Connected to the database. {"timestamp":"2022-07-14T20:02:49.277Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T20:15:33.942Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Projects\\Socially-App\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-07-14T20:16:03.955Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T20:20:21.504Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Projects\\Socially-App\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-07-14T20:20:51.521Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T20:22:05.013Z"}
info: Connected to the database. {"timestamp":"2022-07-14T20:22:07.538Z"}
error: 
      status - 79
      message - No write concern mode named 'majority/SociallyDB' found in replica set configuration 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-14T20:43:37.526Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 79
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.writeHead (node:_http_server:275:11)
    at ServerResponse.writeHead (C:\Projects\Socially-App\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:266:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Projects\Socially-App\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (C:\Projects\Socially-App\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (C:\Projects\Socially-App\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:326:13)
    at C:\Projects\Socially-App\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-14T20:43:37.561Z"}
error: 
      status - 79
      message - No write concern mode named 'majority/SociallyDB' found in replica set configuration 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-14T20:44:04.861Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 79
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.writeHead (node:_http_server:275:11)
    at ServerResponse.writeHead (C:\Projects\Socially-App\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:266:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Projects\Socially-App\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (C:\Projects\Socially-App\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (C:\Projects\Socially-App\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:326:13)
    at C:\Projects\Socially-App\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-14T20:44:04.865Z"}
error: 
      status - 79
      message - No write concern mode named 'majority/SociallyDB' found in replica set configuration 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-14T20:44:49.111Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 79
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.writeHead (node:_http_server:275:11)
    at ServerResponse.writeHead (C:\Projects\Socially-App\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:266:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Projects\Socially-App\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (C:\Projects\Socially-App\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (C:\Projects\Socially-App\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:326:13)
    at C:\Projects\Socially-App\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-14T20:44:49.118Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T20:45:30.842Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Projects\\Socially-App\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Projects\\Socially-App\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Projects\\Socially-App\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-07-14T20:46:00.857Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T20:58:12.269Z"}
info: Connected to the database. {"timestamp":"2022-07-14T20:58:14.784Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T21:20:41.326Z"}
info: Connected to the database. {"timestamp":"2022-07-14T21:20:41.354Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at newUserValidator (C:\Projects\Socially-App\src\validators\/user.validator.js:12:16)
    at Layer.handle [as handle_request] (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Projects\Socially-App\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Projects\Socially-App\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:95:5)
    at C:\Projects\Socially-App\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:328:13)
    at C:\Projects\Socially-App\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:175:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-14T22:04:09.411Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at newUserValidator (C:\Projects\Socially-App\src\validators\/user.validator.js:12:16)
    at Layer.handle [as handle_request] (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Projects\Socially-App\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Projects\Socially-App\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:95:5)
    at C:\Projects\Socially-App\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:328:13)
    at C:\Projects\Socially-App\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:175:3) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-14T22:05:15.416Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T22:05:49.860Z"}
info: Connected to the database. {"timestamp":"2022-07-14T22:05:49.884Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T22:07:35.010Z"}
info: Connected to the database. {"timestamp":"2022-07-14T22:07:35.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T22:07:52.867Z"}
info: Connected to the database. {"timestamp":"2022-07-14T22:07:52.890Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-14T22:08:03.505Z"}
info: Connected to the database. {"timestamp":"2022-07-14T22:08:03.540Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SociallyDB.users index: email_1 dup key: { email: "anitha@gmail.com" } 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-15T00:45:54.322Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.writeHead (node:_http_server:275:11)
    at ServerResponse.writeHead (C:\Projects\Socially-App\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:266:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Projects\Socially-App\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (C:\Projects\Socially-App\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (C:\Projects\Socially-App\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (C:\Projects\Socially-App\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:326:13)
    at C:\Projects\Socially-App\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (C:\Projects\Socially-App\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-15T00:45:54.354Z"}
